### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by cdarken** [OFFLINE-GmbH/oc-bootstrapper#1]
Hi.

I've tried to use your tool to start a new october cms project.

Used october init, replaced just the database connection info and the mail section.
I just get this output:
```
Downloading latest October CMS...
Installing composer dependencies...
Setting up config files...
Migrating Database...
Removing demo data...
Clearing cache...
Installing Theme...
Installing Plugins...
Setting up deployments...
Creating .gitignore...
Creating README...
Cleaning up...
Application ready! Build something amazing.
```
But I still have the demo theme and plugin and no other plugins.
Any hints what could go wrong?
Thanks.

**Comment by tobias-kuendig** [comment]
What system are you running on? Could you paste the contents of your october.yaml file?

Are your settings available in `config/dev/`?

**Comment by cdarken** [comment]
I'm running it on Ubuntu 14.04.

My october.yaml:

```
app:
    url: http://mysite.dev
    locale: en

database:
    connection: mysql
    username: root
    password:
    database: mysite
    host: 127.0.0.1

# theme: goeroe-semantic-october

deployment: false

plugins:
    - Rainlab.Pages
    - Rainlab.Builder
    - Adrenth.Redirect
    - Indikator.Backend
    - OFFLINE.SiteSearch
    - OFFLINE.ResponsiveImages
    # - Vendor.Private (user@remote.git)

mail:
    name: Admin
    address: admin@mysite.dev
    driver: log
```

And the settings are availiable in config/dev.
