### ISSUE TITLE
Composer not found error with Gitlab CI jobs

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#20]
Hi,

I'm having problems with deployment from Gitlab CI.
I always get the same error: `composer: command not found`

````
Running with gitlab-runner 11.0.0 (5396d320)
  on docker-auto-scale ed2dce3a
Using Docker executor with image ruby:2.5 ...
Pulling docker image ruby:2.5 ...
Using docker image sha256:55fb4a37704e96ac8c6c930180e22cf986207d6d39ab03dedc41a608bbd30372 for ruby:2.5 ...
Running on runner-ed2dce3a-project-7222738-concurrent-0 via runner-ed2dce3a-srm-1530581463-a69e7b46...
Cloning repository...
Cloning into '/builds/xxxx/xxxx'...
Checking out xxxxxxx as master...
Skipping Git submodules setup
$ composer global require --prefer-dist laravel/envoy=~1.0 --no-interaction --prefer-dist --quiet
/bin/bash: line 63: composer: command not found
ERROR: Job failed: exit code 1
````
*anonymized data*

I easily admit that the "Gitlab CI with Envoy" section of the readme leaves me perplexed at the reading. 
 - Do I need a special setting for the runner it in Gitlab CI??
 - Do I need a Dockerfile file to configure image?? 

A little more information on the implementation would not be a refusal.

Thank's.

**Comment by tobias-kuendig** [comment]
You are running your pipeline with the `ruby` image. Use the [composer](https://hub.docker.com/_/composer/) image instead.

```yml
deploy:
    image: composer:latest
    only:
        - master
    script:
        - composer global require --prefer-dist laravel/envoy=~1.0 --no-interaction --prefer-dist --quiet
        - envoy run deploy
```

You can find further examples on how to use GitLab CI here:
https://docs.gitlab.com/ce/ci/examples/README.html

**Comment by damsfx** [comment]
> You are running your pipeline with the ruby image.

Ho ... Sorry!
I've seen that but as I'm just using out of the box configuration, I wasn't thinking an update to the file was required.
Don't see the image property in  [oc-bootstrapper/templates/gitlab-ci.yml](https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/7fef0515779f69b31959d7d2e8d0c44a4ebaf1d4/templates/gitlab-ci.yml#L2) !?


That sayed ... 
I'm still getting error : 
````
$ composer global require --prefer-dist laravel/envoy=~1.0 --no-interaction --prefer-dist --quiet
$ envoy run deploy
/bin/bash: line 65: envoy: command not found
````

This is going to make me crazy! :-/

**Comment by tobias-kuendig** [comment]
The shipped `.gitlab-ci.yml` file is two years old already. When the file was written the default GitLab CI setup was using local shell runners. I'm updating it to work out of the box with the current GitLab configuration.

Could you test if this version works?

```
deploy:
    image: composer:latest
    only:
        - master
    script:
        - composer global require --prefer-dist laravel/envoy=~1.0 --no-interaction --prefer-dist --quiet
        - /tmp/vendor/bin/envoy run deploy
```
